# Generated by Django 4.2.25 on 2025-11-08 02:23

from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('flashcard', 'Flashcard Review'), ('pronunciation_practice', 'Pronunciation Practice'), ('vocabulary_review', 'Vocabulary Review'), ('mixed', 'Mixed Practice')], max_length=30)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('items_reviewed', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('translation', 'Translation'), ('speech_to_text', 'Speech to Text'), ('pronunciation', 'Pronunciation Assessment')], max_length=20)),
                ('content', models.JSONField(help_text='Flexible JSON structure based on item type')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('source_language', models.CharField(blank=True, help_text='ISO language code', max_length=10)),
                ('target_language', models.CharField(blank=True, help_text='ISO language code', max_length=10)),
                ('audio_url', models.TextField(blank=True, help_text='S3/storage reference for audio files')),
                ('ease_factor', models.DecimalField(decimal_places=2, default=2.5, max_digits=3, validators=[django.core.validators.MinValueValidator(1.3)])),
                ('interval_days', models.IntegerField(default=0)),
                ('repetitions', models.IntegerField(default=0)),
                ('next_review_date', models.DateField(blank=True, db_index=True, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('quality', models.IntegerField(help_text='0=complete blackout, 5=perfect response', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('time_spent_seconds', models.IntegerField(blank=True, null=True)),
                ('was_correct', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vocalearn.saveditem')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_reviews', to='vocalearn.studysession')),
            ],
            options={
                'db_table': 'item_reviews',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='vocalearn.collection')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_collections', to='vocalearn.saveditem')),
            ],
            options={
                'db_table': 'collection_items',
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', '-started_at'], name='idx_session_user'),
        ),
        migrations.AddIndex(
            model_name='saveditem',
            index=models.Index(fields=['user', 'type'], name='idx_user_type'),
        ),
        migrations.AddIndex(
            model_name='saveditem',
            index=models.Index(fields=['user', 'next_review_date'], name='idx_user_review'),
        ),
        migrations.AddIndex(
            model_name='saveditem',
            index=models.Index(fields=['user', '-created_at'], name='idx_user_created'),
        ),
        migrations.AddIndex(
            model_name='saveditem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idx_search_vector'),
        ),
        migrations.AddIndex(
            model_name='itemreview',
            index=models.Index(fields=['item', '-reviewed_at'], name='idx_review_item'),
        ),
        migrations.AddIndex(
            model_name='itemreview',
            index=models.Index(fields=['session'], name='idx_review_session'),
        ),
        migrations.AddIndex(
            model_name='collectionitem',
            index=models.Index(fields=['collection', 'position'], name='idx_collection_pos'),
        ),
        migrations.AlterUniqueTogether(
            name='collectionitem',
            unique_together={('collection', 'item')},
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['user', '-created_at'], name='idx_collection_user'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('user', 'name')},
        ),
    ]
