# Generated by Django 4.2.25 on 2025-11-13 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocalearn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveditem',
            name='audio_size_bytes',
            field=models.BigIntegerField(default=0, help_text='Size of audio file in bytes'),
        ),
        migrations.CreateModel(
            name='UserStorageQuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('used_bytes', models.BigIntegerField(default=0, help_text='Total bytes used by user')),
                ('quota_bytes', models.BigIntegerField(default=104857600, help_text='Storage quota in bytes (default 100MB)')),
                ('audio_file_count', models.PositiveSmallIntegerField(default=0)),
                ('max_audio_files', models.PositiveSmallIntegerField(default=50, help_text='Maximum number of audio files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_storage_quota',
                'indexes': [models.Index(fields=['user'], name='idx_storage_user')],
            },
        ),
    ]
